name: Release Creation Pipeline
on:
  workflow_dispatch:
    inputs:
      release_name: 
        required: true
        description: release name

jobs:
  Release-Creation:
    runs-on: windows-latest
      
    steps:
      - uses: actions/checkout@v3
        
      - name: Execute Release Creation Script
        run: .github/actions/CreateRelease/CreateRelease1.ps1
        shell: powershell
        env:
          release_name: ${{ inputs.release_name }}
          token: ${{ secrets.LOCAL_TOKEN }}
                
      - name: list files
        run: |
          $path = Get-ChildItem ReleaseCreation-*.csv
          Write-Output $path
          file = $path" >> $env:GITHUB_ENV
          
      - name: Push Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.file }}
          path: ./${{ env.file }}
          retention-days: 10
  
